Expose properties needed for octopus-psd
webtoon/psd pull request #74
Opened 2023-01-10 13:37 UTC by alexspevak

In this pull request, we would like to expose needed properties on Layer and needed types and keys. Also, we added some functionality do be able to decode image patterns.

2023-01-16 10:41 UTC, scoiatael commented
@pastelmind @dlehdanakf who could be a good reviewer here? Since I contributed part of the work to this PR I don't feel like I would be an impartial judge on that :)
Let me know if you need more background on why we want these features :)

2023-01-26 11:23 UTC, scoiatael commented
@alexanderspevak let's convert it to a draft since it seems like there's more work to be done.

2023-01-26 12:00 UTC, alexspevak commented
> @alexanderspevak let's convert it to a draft since it seems like there's more work to be done.

changed.

2023-03-01 09:01 UTC, alexspevak commented
Hi there @pastelmind . Would you be so kind and tell us if we can merge this pull request, or if there are any changes that you would like to amend?

2023-06-28 04:03 UTC, pastelmind commented on packages/psd/src/interfaces/AdditionalLayerInfo/PatternAliBlock.ts
> +export interface PatterDataRectangle {
```suggestion
export interface PatterDataRectangle {
```

2023-06-28 04:11 UTC, pastelmind requested changes
Hi. I apologize for the extreme delay in answering you. This PR looks good!

2023-06-28 04:11 UTC, pastelmind commented on packages/psd/src/interfaces/AdditionalLayerInfo/PatternAliBlock.ts
> +}
```suggestion
export interface PatternDataRectangle {
  top: number;
  left: number;
  bottom: number;
  right: number;
}

export interface PatternDataChannel extends ChannelBytes {
  written: true;
  length: number;
  pixelDepth1: number;
  rectangle: PatternDataRectangle;
  pixelDepth2: number;
}

export interface PatternData {
  version: number;
  length: number;
  rectangle: PatternDataRectangle;
  numberOfChannels: number;
  channels: Map<ChannelKind, PatternDataChannel>;
}
```

2023-06-28 04:11 UTC, pastelmind commented on packages/psd/src/sections/LayerAndMaskInformation/AdditionalLayerInfo/readPatternAliBlock.ts
> +  }
Why make this a Map? Looks like an array would suffice.

2023-06-29 08:51 UTC, pastelmind commented
What if I created a separate PR based on this one, plus the proposed changes? Does this suit you?

2023-07-02 09:00 UTC, scoiatael commented
Yeah, that works :)

2023-07-13 22:37 UTC, pastelmind commented on packages/psd/src/sections/LayerAndMaskInformation/AdditionalLayerInfo/readPatternAliBlock.ts
> +  }
Upon examining the case further, it appears that the key for the Map is supposed to be `ChannelKind`, which can be one of 0, 1, 2, -1, -2, -3:

https://github.com/webtoon/psd/blob/f9ae80c23063b017f1d079d26a562b38ed84063d/packages/psd/src/interfaces/ChannelKind.ts#L7-L14

Perhaps using `ChannelKind` as the key was a mistake? In any case, I will change it to an array.

2023-07-13 22:55 UTC, pastelmind commented
Closing in favor of #93

2023-07-13 22:55 UTC, closed without merging